---
abstract: 'Extract search strings from more referrers.'
author:
  - 'Olaf Alders (olaf@wundersolutions.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-ParseSearchString-More
no_index:
  directory:
    - t
    - inc
requires:
  Config::General: 0
  Data::Dump: 0
  File::Spec: 0
  List::Compare: 0
  Params::Validate: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0.44
  Test::WWW::Mechanize: 0
  URI::Heuristic: 0
  URI::ParseSearchString: 0
  WWW::Mechanize: 0
  WWW::Mechanize::Cached: 1.33
version: 0.14
