--- #YAML:1.0
name:               URI-ParseSearchString-More
version:            0.13
abstract:           Extract search strings from more referrers.
author:
    - Olaf Alders (olaf@wundersolutions.com)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::General:      0
    Data::Dump:           0
    File::Spec:           0
    List::Compare:        0
    Params::Validate:     0
    Test::More:           0
    Test::Pod:            0
    Test::Pod::Coverage:  0
    Test::Simple:         0.44
    Test::WWW::Mechanize:  0
    URI::Heuristic:       0
    URI::ParseSearchString:  0
    WWW::Mechanize:       0
    WWW::Mechanize::Cached:  1.33
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
